FROM microsoft/aspnetcore-build as build-env

WORKDIR /source
COPY MyService/Orchestration/. Orchestration/.

WORKDIR /source/Orchestration

RUN dotnet restore

RUN dotnet publish --output /app/ --configuration Release

FROM microsoft/aspnetcore
WORKDIR /app
COPY --from=build-env /app .

ENTRYPOINT ["dotnet", "WebApi.dll"]